/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  library: [
    'index',
    {
      type: 'category',
      label: 'Quick Start',
      items: [{ type: 'autogenerated', dirName: 'quickstart' }],
    },
    {
      type: 'category',
      label: 'MakeShift Overview',
      items: [{ type: 'autogenerated', dirName: 'makeshift-overview' }],
    },
    {
      type: 'category',
      label: 'APIs',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
