/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  library: [
    'index',
    'overview',
    {
      type: 'category',
      label: '🚧 Quick Start',
      link: {
        type: 'doc',
        id: 'quickstart'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'quickstart'
      }],
    },
    {
      type: 'category',
      label: '🚧 MakeShift In-Depth',
      link: {
        type: 'doc',
        id: 'makeshift-deep-dive'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'makeshift-deep-dive'
      }],
    },
    {
      type: 'category',
      label: '🚧 APIs',
      items: [{
        type: 'autogenerated',
        dirName: 'api'
      }],
    },

  ]
};

module.exports = sidebars;
